import { createContext, useContext } from 'react';

const t = {
  // Hero
  badge: 'AI Entertainment · Dream Analysis',
  heroLine1: 'Decode Your Dreams.',
  heroLine2: 'Explore Your Dreams.',
  heroDesc:
    'AI-powered dream analysis and image generation for entertainment and creative self-reflection. Describe your dream and receive an imaginative, AI-generated interpretation.',
  placeholder: 'Last night, I was flying over a glowing crystal city at dusk. I felt weightless but strangely anxious. A shadowy figure was chasing me from below, and the towers kept shifting from gold to deep blue. Then I woke up just before I landed...',
  analyzeBtn: 'Analyze & Draw',
  analyzing: 'Analyzing...',
  privacy: 'Your entries are private and never shared.',

  // Features
  featuresTitle: 'What DreamLens Offers',
  featuresSubtitle:
    'An AI-powered entertainment experience for exploring the imagery and themes of your dreams.',
  features: [
    {
      title: 'AI Symbol Analysis',
      description:
        'Our AI draws on a wide range of psychological and symbolic frameworks to offer creative, thought-provoking reflections on your dream narratives — for entertainment and self-exploration.',
    },
    {
      title: 'AI Dream Visualization',
      description:
        "Don't just describe it. See it. Generate vivid AI artwork inspired by your dreams using our generative image engine.",
    },
    {
      title: 'Private Dream Journal',
      description:
        'Your dream entries are stored privately. We do not share or sell your personal content to third parties.',
    },
  ],

  // LiveFeed
  galleryTitle: 'Dream Gallery',
  gallerySample: 'Sample Content',
  galleryDesc: 'Illustrative examples of dream analyses. Not real user data.',

  // Footer
  footerDisclaimer:
    'DreamLens is an AI-powered entertainment tool for creative self-reflection. All dream analyses are generated by AI and are intended for entertainment purposes only. They do not constitute professional psychological, medical, or therapeutic advice. Lucky signifiers and fortune content are purely fictional. Always consult a qualified professional for mental health concerns.',
  footerCopy: '© 2025 DreamLens AI. Sweet Dreams.',
  footerContact: 'Contact',
  footerContactEmail: 'wjdtjsdlf210@gmail.com',

  // ResultPage
  resultTitle: 'Dream Analysis',
  tabPsychology: 'Psychology',
  tabFortune: 'Fortune',
  metricsTitle: 'Dream Metrics',
  metricsResonance: 'High Resonance',
  emotionalSpectrum: 'Emotional Spectrum',
  emotionalMixed: 'Mixed',
  deepTitle: 'Deep Analysis',
  adviceTitle: 'Daily Advice',
  luckyTitle: 'Lucky Signifiers',
  luckyDisclaimer: 'For entertainment purposes only. Not a prediction or guarantee.',
  labelNumber: 'Number',
  labelColor: 'Color',
  labelDirection: 'Direction',
  labelTotem: 'Totem',
  resultDisclaimer:
    'This analysis is AI-generated for entertainment and creative self-reflection only. It does not constitute professional psychological or medical advice.',
  radarLabels: ['Good Fortune', 'Creativity', 'Stress', 'Realism', 'Nightmare'],

  // Share / Download
  shareBtn: 'Share',
  shareSaving: 'Saving...',
  shareWatermark: 'Analyzed by DreamLens AI',
  downloadBtn: 'Save Image',

  // Paywall
  unlockBtn: 'Unlock Deep Analysis — $2.88',
  unlockDesc: 'Unlock the full psychological deep analysis, share card & image download.',
  verifying: 'Verifying payment...',
  unlocking: 'Unlocking...',
};

const LanguageContext = createContext(t);

export function LanguageProvider({ children }) {
  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
