import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Header
    langToggle: '한국어',

    // Hero
    badge: 'AI Entertainment · Dream Analysis',
    heroLine1: 'Decode Your Dreams.',
    heroLine2: 'Explore Your Dreams.',
    heroDesc:
      'AI-powered dream analysis and image generation for entertainment and creative self-reflection. Describe your dream and receive an imaginative, AI-generated interpretation — just for fun.',
    placeholder: 'Last night, I was flying over a city made of crystal...',
    analyzeBtn: 'Analyze & Draw',
    analyzing: 'Analyzing...',
    privacy: 'Your entries are private and never shared.',

    // Features
    featuresTitle: 'What DreamLens Offers',
    featuresSubtitle:
      'An AI-powered entertainment experience for exploring the imagery and themes of your dreams.',
    features: [
      {
        title: 'AI Symbol Analysis',
        description:
          'Our AI draws on a wide range of psychological and symbolic frameworks to offer creative, thought-provoking reflections on your dream narratives — for entertainment and self-exploration.',
      },
      {
        title: 'AI Dream Visualization',
        description:
          "Don't just describe it. See it. Generate vivid AI artwork inspired by your dreams using our generative image engine.",
      },
      {
        title: 'Private Dream Journal',
        description:
          'Your dream entries are stored privately. We do not share or sell your personal content to third parties.',
      },
    ],

    // LiveFeed
    galleryTitle: 'Dream Gallery',
    gallerySample: 'Sample Content',
    galleryDesc: 'Illustrative examples of dream analyses. Not real user data.',

    // Footer
    footerDisclaimer:
      'DreamLens is an AI-powered entertainment tool for creative self-reflection. All dream analyses are generated by AI and are intended for entertainment purposes only. They do not constitute professional psychological, medical, or therapeutic advice. Lucky signifiers and fortune content are purely fictional. Always consult a qualified professional for mental health concerns.',
    footerCopy: '© 2025 DreamLens AI. Sweet Dreams.',

    // ResultPage
    resultTitle: 'Dream Analysis',
    tabPsychology: 'Psychology',
    tabFortune: 'Fortune',
    metricsTitle: 'Dream Metrics',
    metricsResonance: 'High Resonance',
    emotionalSpectrum: 'Emotional Spectrum',
    emotionalMixed: 'Mixed',
    deepTitle: 'Deep Analysis',
    adviceTitle: 'Daily Advice',
    luckyTitle: 'Lucky Signifiers',
    luckyDisclaimer: 'For entertainment purposes only. Not a prediction or guarantee.',
    labelNumber: 'Number',
    labelColor: 'Color',
    labelDirection: 'Direction',
    labelTotem: 'Totem',
    resultDisclaimer:
      'This analysis is AI-generated for entertainment and creative self-reflection only. It does not constitute professional psychological or medical advice.',
    radarLabels: ['Good Fortune', 'Creativity', 'Stress', 'Realism', 'Nightmare'],
  },

  ko: {
    // Header
    langToggle: 'English',

    // Hero
    badge: 'AI 엔터테인먼트 · 꿈 분석',
    heroLine1: '꿈을 해석하다.',
    heroLine2: '꿈을 탐험하다.',
    heroDesc:
      'AI 기반 꿈 분석과 이미지 생성으로 창의적 자기 탐색을 경험해보세요. 꿈을 설명하면 AI가 상상력 풍부한 해석을 제공합니다 — 순수한 재미를 위해.',
    placeholder: '어젯밤, 수정으로 만들어진 도시 위를 날고 있었어요...',
    analyzeBtn: '분석 & 그리기',
    analyzing: '분석 중...',
    privacy: '입력 내용은 비공개이며 공유되지 않습니다.',

    // Features
    featuresTitle: 'DreamLens가 제공하는 것',
    featuresSubtitle: 'AI 기반 엔터테인먼트로 꿈의 이미지와 주제를 탐구하는 경험.',
    features: [
      {
        title: 'AI 심볼 분석',
        description:
          'AI가 다양한 심리적·상징적 프레임워크를 활용하여 꿈 내러티브에 대한 창의적이고 흥미로운 해석을 제공합니다 — 엔터테인먼트와 자기 탐구를 위해.',
      },
      {
        title: 'AI 꿈 시각화',
        description:
          '단순히 설명하지 말고, 직접 보세요. AI 이미지 엔진으로 꿈에서 영감을 받은 생생한 아트워크를 생성하세요.',
      },
      {
        title: '프라이빗 꿈 일지',
        description:
          '꿈 기록은 비공개로 저장됩니다. 개인 콘텐츠를 제3자와 공유하거나 판매하지 않습니다.',
      },
    ],

    // LiveFeed
    galleryTitle: '꿈 갤러리',
    gallerySample: '샘플 콘텐츠',
    galleryDesc: '꿈 분석의 예시 콘텐츠입니다. 실제 사용자 데이터가 아닙니다.',

    // Footer
    footerDisclaimer:
      'DreamLens는 창의적 자기 탐색을 위한 AI 엔터테인먼트 도구입니다. 모든 꿈 분석은 AI가 생성하며 순수한 엔터테인먼트 목적으로만 제공됩니다. 전문적인 심리적, 의학적 또는 치료적 조언을 구성하지 않습니다. 행운의 상징과 운세 콘텐츠는 순전히 픽션입니다. 정신 건강 문제는 항상 전문가와 상담하세요.',
    footerCopy: '© 2025 DreamLens AI. 달콤한 꿈 되세요.',

    // ResultPage
    resultTitle: '꿈 분석',
    tabPsychology: '심리',
    tabFortune: '운세',
    metricsTitle: '꿈 지표',
    metricsResonance: '높은 공명',
    emotionalSpectrum: '감정 스펙트럼',
    emotionalMixed: '복합',
    deepTitle: '심층 분석',
    adviceTitle: '오늘의 조언',
    luckyTitle: '행운의 징표',
    luckyDisclaimer: '엔터테인먼트 목적으로만 제공됩니다. 예측이나 보장이 아닙니다.',
    labelNumber: '숫자',
    labelColor: '색상',
    labelDirection: '방향',
    labelTotem: '토템',
    resultDisclaimer:
      '이 분석은 엔터테인먼트와 창의적 자기 탐색을 위해 AI가 생성한 것입니다. 전문적인 심리적 또는 의학적 조언을 구성하지 않습니다.',
    radarLabels: ['행운', '창의성', '스트레스', '현실감', '악몽'],
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ko');
  const toggle = () => setLang((l) => (l === 'ko' ? 'en' : 'ko'));
  return (
    <LanguageContext.Provider value={{ lang, toggle, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
