import { useState } from 'react';

const FAQS = [
  {
    q: 'What is DreamLens?',
    a: 'DreamLens is a free AI-powered dream interpretation service. You describe a dream, and our AI generates a multi-framework analysis drawing on Jungian psychology, Freudian theory, Korean Taemong tradition, and Chinese Zhou Gong symbolism — along with an AI-generated artwork inspired by your dream.',
  },
  {
    q: 'Is DreamLens free to use?',
    a: 'Yes. The core dream analysis and dream visualization features are completely free. No account, no subscription, and no payment is required. An optional Deep Analysis upgrade is available for a one-time fee if you want the full psychological breakdown, dream share card, and image download.',
  },
  {
    q: 'Are my dreams kept private?',
    a: 'Your dream text is sent to the Gemini AI API to generate your analysis, but it is not stored on our servers. Your entry is held in your browser\'s session storage for the duration of your visit only and is cleared when you close the tab. We do not build a database of user dream entries.',
  },
  {
    q: 'What is Jungian dream analysis?',
    a: 'Jungian analysis, developed by psychiatrist Carl Jung, interprets dreams as communications from the unconscious mind. It focuses on universal symbols called archetypes — the Shadow, the Anima/Animus, the Hero, the Self — and explores how they appear in your dreams to reflect inner psychological processes.',
  },
  {
    q: 'What is Freudian dream analysis?',
    a: 'Freudian analysis, developed by Sigmund Freud, views dreams as disguised expressions of unconscious wishes. It distinguishes between the manifest content (what you literally dream) and the latent content (the underlying psychological meaning), paying close attention to symbols, emotional tone, and recurring motifs.',
  },
  {
    q: 'What is Taemong (태몽)?',
    a: 'Taemong is a Korean tradition of interpreting "pregnancy dreams" — vivid dreams believed to foretell the birth and character of an unborn child. Common Taemong symbols include animals (tigers, dragons, fish), natural phenomena (sunrises, fruit), and celestial objects. The tradition reflects centuries of Korean cultural wisdom about the relationship between dreams and destiny.',
  },
  {
    q: 'What is Zhou Gong Dream Interpretation (周公解梦)?',
    a: 'Zhou Gong Jie Meng, attributed to the Duke of Zhou from ancient China (circa 1100 BCE), is one of the world\'s oldest dream dictionaries. It catalogues thousands of dream scenarios and interprets them as omens of fortune or misfortune. This tradition remains deeply embedded in Chinese culture and is still consulted today.',
  },
  {
    q: 'Can I use DreamLens for mental health support?',
    a: 'DreamLens is an entertainment and creative self-reflection tool. It is not a clinical product and its analyses are not professional psychological or medical advice. If you are experiencing distressing recurring dreams, sleep disorders, or mental health concerns, please consult a qualified mental health professional.',
  },
  {
    q: 'How accurate are the interpretations?',
    a: 'Dream interpretation is inherently subjective and symbolic — there is no single "correct" meaning for any dream. DreamLens generates interpretations that are thoughtful, culturally grounded, and creatively engaging, but they represent one perspective among many. Think of them as a starting point for your own reflection, not a definitive verdict.',
  },
  {
    q: 'What AI technology does DreamLens use?',
    a: 'DreamLens uses Google\'s Gemini AI models for both text analysis and dream image generation. The interpretation is generated by a large language model trained on a broad range of psychological, literary, and cultural sources.',
  },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-white/10 rounded-2xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left px-6 py-5 flex items-center justify-between gap-4 hover:bg-white/5 transition-colors"
      >
        <span className="font-semibold text-white">{q}</span>
        <span className={`material-symbols-outlined text-primary shrink-0 transition-transform duration-200 ${open ? 'rotate-180' : ''}`}>
          expand_more
        </span>
      </button>
      {open && (
        <div className="px-6 pb-5 text-gray-300 text-sm leading-relaxed border-t border-white/10 pt-4">
          {a}
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <section className="max-w-3xl mx-auto px-4 sm:px-6 mb-16 md:mb-32">
      <div className="text-center mb-8 md:mb-12">
        <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Frequently Asked Questions</h2>
        <p className="text-gray-400 max-w-lg mx-auto leading-relaxed text-sm md:text-base px-2">
          Everything you need to know about DreamLens and AI dream interpretation.
        </p>
      </div>
      <div className="space-y-3">
        {FAQS.map((item) => (
          <FAQItem key={item.q} q={item.q} a={item.a} />
        ))}
      </div>
    </section>
  );
}
